const GLOBAL_EVENT_BUS_FOR_SNACK_BAR = 'showSnackBarMsg';

const SPACEX_HOME = 'Home';
const SPACEX_LAUNCHES = 'Launches';
const SPACEX_LAUNCH_PADS = 'Launch Pads';
const SPACEX_ROCKETS = 'Rockets';
const SPACEX_SHIPS = 'Ships';
const SPACEX_CAPSULES = 'Capsules';
const SPACEX_CREWS = 'Crews';

const SPACEX_LAUNCHES_SORT_BY_DATE_DESC_API_ENDPOINT = 'launches/query';
const SPACEX_LAUNCHES_API_ENDPOINT = 'launches';
const SPACEX_COMPANY_INFO_API_ENDPOINT = 'company';

export default {
  GLOBAL_EVENT_BUS_FOR_SNACK_BAR,
  SPACEX_LAUNCHES_SORT_BY_DATE_DESC_API_ENDPOINT,
  SPACEX_LAUNCHES_API_ENDPOINT,
  SPACEX_COMPANY_INFO_API_ENDPOINT,

  SPACEX_HOME,
  SPACEX_LAUNCHES,
  SPACEX_LAUNCH_PADS,
  SPACEX_ROCKETS,
  SPACEX_SHIPS,
  SPACEX_CAPSULES,
  SPACEX_CREWS,
};
